name: CI

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Use Ruby 
      uses: actions/setup-ruby@v1
      with:
        version: 2.x
    - name: install nodejs
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: install awesome_bot
      run: gem install awesome_bot
    - name: install danger
      run: gem install danger
    - name: get changes only
      run: git diff master.. -U0 README.md | grep -Pos "(?<=^\+).*" >> temp.md || (exit 0)
    - name: test
      run: node tests/test.js temp.md
    - name: awesome_bot
      run: awesome_bot temp.md --allow-redirect || (exit 0)
    - name: Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: danger --dangerfile=tests/Dangerfile --verbose
